### ISSUE TITLE
502 for some, but not all, POST requests in Dockerized uMap behind NGINX reverse proxy

### ISSUE THREAD

**Issue by sircharlo** [umap-project/umap#1353]
**Describe the bug**
For a reason I can't quite understand, I get 502 errors when attempting some operations, but not others, when behind an NGUNX reverse proxy.

**To Reproduce**
Here is the services section of my docker-compose.yml:

```
  umap-db:
    container_name: umap-db
    image: postgis/postgis:16-3.4-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - /media/domain/Container-Data/umap/db:/var/lib/postgresql/data

  umap-app:
    container_name: umap-app
    image: umap/umap:1.8.2
    ports:
      - "8414:8000"
    environment:
      - DATABASE_URL=postgis://postgres@umap-db/postgres
      - SITE_URL="https://domain.duckdns.org:8414"
      - STATIC_ROOT=/srv/umap/var/static
      - MEDIA_ROOT=/srv/umap/var/data
    volumes:
      - /media/domain/Container-Data/umap/userdata:/srv/umap/uploads
      - /media/domain/Container-Data/umap/umap.conf:/etc/umap/umap.conf
    depends_on:
      - umap-db
```

Here is the .conf file for my reverse proxy:
```
server {
  listen 8415 ssl;
  ssl_certificate /etc/ssl/live/domain.duckdns.org/fullchain.pem;
  ssl_certificate_key /etc/ssl/live/domain.duckdns.org/privkey.pem;

  location / {
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://192.168.1.100:8414;
  }
}

```

**Expected behavior**
Navigate to https://domain.duckdns.org and use all parts of the site.

**Actual behavior**
Creating maps works fine, but adding point and saving gives 502 errors.

**Screenshots**
Failed:

![image](https://github.com/umap-project/umap/assets/1275666/1b46b947-8886-4dad-bd16-b3ee2e33436b)

Successful:

![image](https://github.com/umap-project/umap/assets/1275666/0334f073-2070-4512-9d1e-ce433ac9bea5)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome, latest
