### ISSUE TITLE
502 error dockerized uMap behind NGINX Proxy server

### ISSUE THREAD

**Issue by lorenzdomb** [umap-project/umap#1495]
**Describe the bug**
After starting the docker containers I can't get access to the site. There is only 502 Bad Gateway.

**To Reproduce**
```
version: '3'
services:
  db:
    # check https://hub.docker.com/r/postgis/postgis to see available versions
    image: postgis/postgis:14-3.4-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - umap_db:/var/lib/postgresql/data

  app:
    # Check https://hub.docker.com/r/umap/umap/tags to find the latest version
    image: umap/umap:1.3.7
    ports:
      # modify the external port (8001, on the left) if desired, but make sure >
      - "8041:8000"
    environment:
      - DATABASE_URL=postgis://postgres@db/postgres
      - SITE_URL="https://xyz.abc-di.de:8041"
      - STATIC_ROOT=/srv/umap/static
      - MEDIA_ROOT=/srv/umap/uploads
    volumes:
      - umap_userdata:/srv/umap/uploads
      # FIX the path on the left, below, to your location 
      - /home/ubuntu/umap.conf:/etc/umap/umap.conf
    restart: always
    depends_on:
      - db

volumes:
  umap_userdata:
  umap_db:
```

**Expected behavior**
Open the Site https://xyz.abc-di.de in browser an working with it.

**Desktop (please complete the following information):**
 - OS: IOS
 - Browse: Chrome and Safari

**Logs**
```
Attaching to umap_app_1, umap_db_1
db_1   | 
db_1   | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1   | 
db_1   | 2023-12-28 11:54:59.285 UTC [1] LOG:  starting PostgreSQL 14.10 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
db_1   | 2023-12-28 11:54:59.285 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1   | 2023-12-28 11:54:59.285 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1   | 2023-12-28 11:54:59.290 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1   | 2023-12-28 11:54:59.299 UTC [23] LOG:  database system was shut down at 2023-12-28 11:54:53 UTC
db_1   | 2023-12-28 11:54:59.306 UTC [1] LOG:  database system is ready to accept connections
app_1  | Waiting for database to respond...
app_1  | [Errno 21] Is a directory: '/etc/umap/umap.conf'
app_1  | Waiting for database to respond...
app_1  | [Errno 21] Is a directory: '/etc/umap/umap.conf'
app_1  | Waiting for database to respond...
app_1  | [Errno 21] Is a directory: '/etc/umap/umap.conf'
app_1  | Waiting for database to respond...
app_1  | [Errno 21] Is a directory: '/etc/umap/umap.conf'
app_1  | Waiting for database to respond...
app_1  | [Errno 21] Is a directory: '/etc/umap/umap.conf'
app_1  | Waiting for database to respond...
app_1  | [Errno 21] Is a directory: '/etc/umap/umap.conf'
app_1  | Waiting for database to respond...
app_1  | [Errno 21] Is a directory: '/etc/umap/umap.conf'
app_1  | Waiting for database to respond...
app_1  | [Errno 21] Is a directory: '/etc/umap/umap.conf'
app_1  | Waiting for database to respond...
app_1  | [Errno 21] Is a directory: '/etc/umap/umap.conf'
app_1  | Waiting for database to respond...
app_1  | [Errno 21] Is a directory: '/etc/umap/umap.conf'
app_1  | Waiting for database to respond...
app_1  | [Errno 21] Is a directory: '/etc/umap/umap.conf'
app_1  | Waiting for database to respond...
app_1  | [Errno 21] Is a directory: '/etc/umap/umap.conf'
app_1  | Waiting for database to respond...
app_1  | [Errno 21] Is a directory: '/etc/umap/umap.conf'
app_1  | Waiting for database to respond...
app_1  | [Errno 21] Is a directory: '/etc/umap/umap.conf'
app_1  | Waiting for database to respond...
app_1  | [Errno 21] Is a directory: '/etc/umap/umap.conf'
app_1  | Waiting for database to respond...
app_1  | [Errno 21] Is a directory: '/etc/umap/umap.conf'
app_1  | Waiting for database to respond...
app_1  | [Errno 21] Is a directory: '/etc/umap/umap.conf'
app_1  | Waiting for database to respond...
app_1  | [Errno 21] Is a directory: '/etc/umap/umap.conf'
app_1  | Waiting for database to respond...
app_1  | [Errno 21] Is a directory: '/etc/umap/umap.conf'
app_1  | Waiting for database to respond...
app_1  | [Errno 21] Is a directory: '/etc/umap/umap.conf'
app_1  | Waiting for database to respond...
app_1  | [Errno 21] Is a directory: '/etc/umap/umap.conf'
app_1  | Waiting for database to respond...
app_1  | [Errno 21] Is a directory: '/etc/umap/umap.conf'
app_1  | Waiting for database to respond...
app_1  | [Errno 21] Is a directory: '/etc/umap/umap.conf'
```
