### ISSUE TITLE
Feedbacks on the "Import data" panel to rebalance the font sizes

### ISSUE THREAD

**Issue by Aurelie-Jallut** [umap-project/umap#1911]
**Is your feature request related to a problem? Please describe.**
text hierarchy helps users understand the panel

**Describe the solution you'd like**

```css
h3 {
  font-size: 1rem;
}

fieldset legend {
  font-size: 0.9rem;
  padding: 0 5px;
}

.panel .counter {
  display: block;
  margin-top: var(--panel-gutter);
  font-weight: normal;
}

h4 {
  font-size: 0.9rem;
}

.importers ul [type="button"] {
  background: none;
    background-color: rgba(0, 0, 0, 0);
  font-size: 0.75rem;
  border: none;
  width: initial;
  display: inline-block; 
}
```
