### ISSUE TITLE
Login page is blank

### ISSUE THREAD

**Issue by tbornon** [umap-project/umap#2065]
Hello,

I can't log to my umap website using the [lang]/login page. The page is totally blank. However, the login with the admin page.

**To Reproduce**
1. Install umap using docker :
```yaml
version: '3'

services:

  db:
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 2s
    image: postgis/postgis:14-3.3-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db:/var/lib/postgresql/data

  app:
    depends_on:
      db:
        condition: service_healthy
    image: umap/umap:2.5.1
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgis://postgres@db/postgres
      - SECRET_KEY=REDACTED
      - SITE_URL=REDACTED
      - UMAP_ALLOW_ANONYMOUS=False
      - VIRTUAL_HOST=REDACTED
      - VIRUTAL_PORT=8000
      - DEBUG=1
    volumes:
      - data:/srv/umap/uploads

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "192.168.20.115:80:80"
      - "192.168.20.115:443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs

volumes:
  data:
  db:
```

**Screenshots**
Login page
![image](https://github.com/user-attachments/assets/464e3d68-df90-4c19-8aaf-c31e6d2d119d)

**Installed on:**
 - Debian 11
 - Docker engine 20.10.17
 - Umap 2.5.1

Do not hesitate if you need additional information
