### ISSUE TITLE
Placeholder text position in <textarea>

### ISSUE THREAD

**Issue by adriennn** [umap-project/umap#240]
In the **Import data** menu, the placeholder position in the `<textarea>` looks wrong (tested in chrome/ff). 

Adding  `padding-top` and `padding-left` to `#storage-ui-container textarea in the file `umap/umap/static/umap/umap.css` makes it look closer to the placeholder in  a `<input>`

```css
#storage-ui-container textarea {
    height: 100px;
    margin-bottom: 14px;
    margin-top: 5px;
    line-height: normal;
    padding-top: 12px;
    padding-left: 8px;
}
```
