### ISSUE TITLE
Submit login form 403 (after update to 3.0.3)

### ISSUE THREAD

**Issue by lippoliv** [umap-project/umap#2655]
**Describe the bug**
After updating to 3.0.3 (inkl. adding nginx as reverse proxy as discussed here #2648), I can't login any longer. I get 

**To Reproduce**
1. Go to 'https://maps.keine.cloud/de/login/'
2. Put in any credentials (demo / demo or so)
3. Submit

**Expected behavior**
Error about invalid credentials.

**Screenshots**

<img width="1441" alt="Image" src="https://github.com/user-attachments/assets/6ffd160e-f897-4a25-b511-e5f5b2ad9214" />

**Desktop (please complete the following information):**
- OS: MacOS
- Browser Brave
- Version 1.76

**Additional context**
I already tested to set `CSRF_TRUSTED_ORIGINS` and `CORS_ORIGIN_WHITELIST`.
I cant find anything about CSRF in docs.

**Comment by lippoliv** [comment]
I read a little code, googled around and it just made no sense. Then I git-compared 3.0.4 with 2.9.3 and couldn't find anything that should trigger this as well.

In #1178 I found that there's a `X-CSRFToken` that should be ensured to let through reverse proxy to umap. It didn't help (as long as I did it right).

I spun up a fresh environment locally, same issue here.

# Files
I'll share all my relevant files, hopefully someone can tell me the issue.

## docker-compose.yml
```yml
services:
  db:
    image: postgis/postgis:14-3.3-alpine
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - type: bind
        source: ./db
        target: /var/lib/postgresql/data

  app:
    image: umap/umap:3.0.4
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgis://postgres@db/postgres
      - SECRET_KEY=localhost
      - SITE_URL=http://localhost:8081/
      - UMAP_ALLOW_ANONYMOUS=False
      - DEBUG=1
      - ENABLE_ACCOUNT_LOGIN=1
      - LANGUAGE_CODE="en"
    volumes:
      - type: bind
        source: ./data
        target: /srv/umap/uploads
      - type: bind
        source: ./static
        target: /srv/umap/static

  proxy:
    build:
      context: nginx
    expose:
      - 80
    ports:
      - "8081:80"
    volumes:
      - type: bind
        source: ./static
        target: /static
        read_only: true
      - type: bind
        source: ./data
        target: /data
        read_only: true
    depends_on:
      - app
```

## nginx/Dockerfile
```
FROM nginx:1.27.4-alpine

ADD nginx.conf /etc/nginx/nginx.conf
```

## nginx/nginx.conf
```
events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    upstream umap {
        server app:8000;
    }

    server {
        listen 80;
        listen [::]:80;

        charset utf-8;

        client_max_body_size 5M;  # adjust to taste

        location /static {
            autoindex off;
            access_log off;
            log_not_found off;
            sendfile on;
            gzip on;
            gzip_vary on;
            alias /static/;
        }

        location /uploads {
            autoindex off;
            sendfile on;
            gzip on;
            gzip_vary on;
            alias /data/;

            # Exclude direct access to geojson, as permissions must be checked by Django.
            location /uploads/datalayer/ {
                return 404;
            }
        }

        location / {
            proxy_pass http://umap;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-CSRFToken $http_x_csrftoken;

            uwsgi_param QUERY_STRING $query_string;
            uwsgi_param REQUEST_METHOD $request_method;
            uwsgi_param CONTENT_TYPE $content_type;
            uwsgi_param CONTENT_LENGTH $content_length;
            uwsgi_param REQUEST_URI $request_uri;
            uwsgi_param PATH_INFO $document_uri;
            uwsgi_param DOCUMENT_ROOT $document_root;
            uwsgi_param SERVER_PROTOCOL $server_protocol;
            uwsgi_param REQUEST_SCHEME $scheme;
            uwsgi_param HTTPS $https if_not_empty;
            uwsgi_param REMOTE_ADDR $remote_addr;
            uwsgi_param REMOTE_PORT $remote_port;
            uwsgi_param SERVER_PORT $server_port;
            uwsgi_param SERVER_NAME $server_name;
        }
    }
}
```
