### ISSUE TITLE
Since version 3.0 the website is no longer rendered correctly

### ISSUE THREAD

**Issue by geimist** [umap-project/umap#2659]
After an update (umap via docker) from 2.9.3 to 3.x, the website is no longer rendered correctly. The map view remains completely blank and the landing page is broken (see screenshot).

Is it now mandatory to set up a proxy (nginx), or only if you want to use real-time map editing? From the [changelog of v3.0.0](https://docs.umap-project.org/en/master/changelog/#300-2025-04-07) I understood it this way.

If so, where can I find a tutorial for the necessary adjustments?

My compose.yaml. looks like this (and works up to 2.9.3) and in my opinion corresponds to the current [sample configuration](https://docs.umap-project.org/en/master/deploy/docker/):

```YAML
version: '3'
# https://docs.umap-project.org/en/master/deploy/docker/
services:
  db:
    image: postgis/postgis:14-3.4-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./umap/POSTGRESQL_DATA:/var/lib/postgresql/data

  app:
    image: umap/umap:3.0.4
    ports:
      - "8031:8000"
    environment:
      - DATABASE_URL=postgis://postgres@db/postgres
      - SITE_URL=https://map.example.com/
      - STATIC_ROOT=/srv/umap/static
      - MEDIA_ROOT=/srv/umap/uploads
      - SECRET_KEY=xxx
    volumes:
      - ./conf/umap.conf:/etc/umap/umap.conf
      - ./umap/STATIC_ROOT:/srv/umap/static
      - ./umap/MEDIA_ROOT:/srv/umap/uploads
    depends_on:
      - db

```

![Image](https://github.com/user-attachments/assets/94900196-8df1-48dc-b31a-a38a45604e31)
