### ISSUE TITLE
FR / The State of uMap 🗺️

### ISSUE THREAD

**Issue by AntoninCurtit** [umap-project/umap#910]
| ![uMap1](https://user-images.githubusercontent.com/30950182/118690576-7d843e80-b808-11eb-8218-4b79b925d1e3.png) | ![uMap2](https://user-images.githubusercontent.com/30950182/118691165-1450fb00-b809-11eb-8522-4531a8d49001.png) |
|--|--|

# Objectifs
- Rendre uMap plus agréable à utiliser, de bout en bout.
- Rendre cohérents les éléments. Les marges, la hiérarchie, les styles…
- Moderniser l'outil, corriger « ses défauts » : Texte trop fin, trop petit...

# À décider
- Les marges après les titres doivent être définies en amont par les développeurs, ou en aval par les utilisateurs via un retour à la ligne (rendu `<br>`).
    - Devra potentiellement être reflété pour `<hr>`, quia  des marges définies en amont.
- La largeur de la popup, ici rien n'a été retouché.

# À faire
- Ajouter les polices d'écriture. ([Git uMap](https://github.com/umap-project/umap/tree/7893ff1c7d943b7fb71b74dbd8a3b47b7b104ca3/umap/static/umap/font) – [Git Fira](https://github.com/mozilla/Fira))
    - Seules les polices de graisse "Light" et "Semibold" sont actuellement incluses. Ajouter Regular (400 – par défaut) et Bold (700 – `<strong>`) .
    - Pour s'aider : https://github.com/mozilla/Fira/blob/master/fira.css
    - Harmoniser mes propositions/les polices avec le code source ?

# Notes
- Fira Sans est installé sur ma machine, ce qui *peut* fausser le code.
- Testé sur un moniteur 1920×1080, Firefox.
- 16 px : C'est la taille de texte minimale recommandé généralement pour une bonne lecture. J'ai ici choisi 15 px, je pense qu'en fonction du contexte dans lequel le texte est utilisé, la taille peut varier.
- Les espaces entre les lignes, non-signalés, sont des retours à la ligne `<br>`.
- Il va être grandement facile de rejeter ce travail car « ça change ».
- Ci-dessous, le code « brut ». Il peut être utilisé dans les cartes uMap existantes pour avoir un aperçu du style proposé.
    - Note : Cette proposition peut « casser » le style défini actuel. (La suppression des marges sous `<h4>` / `<h5>` va rapprocher le texte des titres, il faudra peut-être remettre des retours à la ligne pour « aérer » le tout, si besoin. C'est mineur.)

``` css
.umap-popup-container {
	font-size: 15px;
	font-weight: 400;
	font-family: 'Fira Sans';
}

.umap-popup-container h3 {
	font-size: 1.5em;
}

.umap-popup-container h4 {
	font-size: 1.2em;
	margin-bottom: 0;
}

.umap-popup-container h5 {
	font-size: 1.1em;
	margin-bottom: 0;
}

.umap-popup-container hr {
	margin: 1.5em auto;
	border: 1px solid #AAA;
}

.umap-popup-container a {
    font-family: 'Fira Sans';
}
```
